package Day33.Enum1;

public enum BookCategory {
    // CTRL+SHIFT+U TO MAKE THEM UPPER_CASE
    NOVEL, SCIENCI_FICTION, HISTORY, CLASSIC, ADVENTURE, FICTION,
    FANTASY, COMICS, MAGAZINES, DETECTIVE,ECONOMY;
}
